<?php

module_load_include('inc','redmineform','content/redmineform.createAdminForm');
module_load_include('inc','redmineform','content/redmineform.createSupportForm');

function redmineform_menu()
{
    $items = array();
    $items['redmine/supportform'] = array(
        'page callback' => 'drupal_get_form',
        'description' => 'Formular zum Absenden einer Supportanfrage',
        'title' => 'Ticketformular',
        'page arguments' => array('redminesupport_form',2),        
        'access arguments' => array('administer redmineform form'),
    );
    $items['admin/config/administration/redmineapi'] = array(
        'title' => 'Redmine API',
        'description' => 'Parameter zur Redmine API festlegen',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('redmineapi_configure'),
        'access arguments' => array('administer redmineform settings'),
    );
    return $items;
}

function redmineform_permission() 
{
    $permissions = array();
    $permissions['administer redmineform settings'] = array(
        'title' => t('Administer Redmine Ticket Settings'),
        'description' => t('Perform administration tasks for Redmine Settings.'),
      );
    $permissions['administer redmineform form'] = array(
        'title' => t('Administer Redmine Ticket Formular'),
        'description' => t('Perform administration tasks for Redmine ticket formular.'),
      );
    return $permissions;
}